### ISSUE TITLE
npm run build removes placeholder directory

### ISSUE THREAD

**Issue by r-hannuschka** [q2g/q2g-ext-bookmark#42]
Sobald npm run build ausgeführt wird, wird auch das placeholder Verzeichnis gelöscht, was wieder rum dazu führt das im GIT das Verzeichnis und alle darin enthaltenen Dateien als deleted gelten was beim nächsten Push dazu führen würde das der Ordner sowie enthaltenen Dateien beim nächsten Pull gelöscht werden.

Den Ordner in die .gitignore zu setzen wird auch nicht funktionieren da beim nächsten clone der Ordner placeholder ignoriert wird und nicht mehr mitkommt.

**Comment by konne** [comment]
ja ich bin mir des Problems bewusst, der PlaceHolder Ordner ist aber nur für "DUMME" Git Clone User die das Readme nicht sauber lesen und muss daher auch nur beim 1. git clone mit kommen, danach darf er gerne weg sein und muss auch nie wieder aktualisiert werden.

**Comment by r-hannuschka** [comment]
Gut dann muss aber dafür gesorgt werden das es beim nächsten commit nicht gelöscht ist sonst wandert es ins GIT und ist dann auch für "Dumme" nicht mehr existent die es clonen :) 

Das kann halt passieren wenn jemand im Halbschlaf git add --all macht und vergisst das placeholder Verzeichnis nochmal auszuchecken da es beim build:dev auch gelöscht wurde oder generell beim npm run build Befehl.

**Comment by konne** [comment]
das finde ich komisch, wenn es im .gitignore ist, dass sollte ihm auch ein git add -all nichts anhabne, aber lass uns das nachher nochmal in ruhe bepsrechn

**Comment by thomashaenig** [comment]
@r-hannuschka hi, what is the status on this issue?

**Comment by r-hannuschka** [comment]
Müssen wir nochmal konkret austesten,  aber ich denk wenn etwas im git ist und nachträglich der .gitignore hinzugefügt wird die .gitignore komplett ignoriert wird. Das sollten wir nochmal konkret testen ob sich das wirklich so verhält. 

Weil wenn ja wäre hier eine Möglichkeit, das wenn der pull request auf master kommt und das verzeichniss nicht mehr existiert das automatisch dieses verzeichniss angelegt wird. So kann es Dir am Ende egal sein ob das irgendwer mal gelöscht hat.

Bin mir aber nicht sicher ob sich der Aufwand hier lohnt nur weil jemand die source files geladen hat und das als extension direkt so reinkopiert.
