### ISSUE TITLE
App wird nicht korrekt initialisiert

### ISSUE THREAD

**Issue by r-hannuschka** [q2g/q2g-ext-bookmark#43]
q2g-ext-bookmark.ts 309:8

`logging.LogConfig.SetLogLevel("*", (scope as any).layout.properties.loglevel);` 

Ist zu dem Zeitpunkt noch nicht korrekt gesetzt, hierbei handelt es sich um ein Timing Problem das layout.properties zu dem Zeitpunkt nicht korrekt initialisiert wurde. Sollte die Javascript Ausführung unterbrechen und den Browser erst einmal rendern lassen funktioniert alles wie gewünscht.  Das hat in der Regel damit was zu tun das der Browser zu dem Zeitpunkt noch nicht alles korrekt gerendert hat.

```
        window.setTimeout( () => {
            //#region Logger
            logging.LogConfig.SetLogLevel("*", (scope as any).layout.properties.loglevel);
            let logger = new logging.Logger("Main");
            //#endregion
        }, 0);
```

**Comment by konne** [comment]
1. ich mag kein windows.setTimeout
2. sollte hier das LogLevel initial erstmal auf ein niedriges Level z.B. Error gesetz twerden
und dann später wenn die extension geladen ist und die Properties eh ausgelesen worden (getProperties)
das LogLevel neu gesetzt werden.
@thomashaenig DON'T Use .layout.properties .... any more !!!
