### ISSUE TITLE
publish arrows greyed out with Qlik November Update

### ISSUE THREAD

**Issue by QlikPana** [q2g/q2g-ext-bookmark#59]
With the Qlik Sense November 2018 Patch 1 update the publish arrows are greyed out.

**Comment by konne** [comment]
@thomashaenig please can you have a look at this issue

**Comment by thomashaenig** [comment]
@QlikPana sorry could not readjust this issue:
can you please check again and send a screenshot?
![image](https://user-images.githubusercontent.com/17725886/54344550-66060580-4641-11e9-8f43-2427bb1d1136.png)

**Comment by QlikPana** [comment]
still not working. please find the attached screenshot. could we have a remote session?
![grafik](https://user-images.githubusercontent.com/48288038/54414643-1afbf900-46fa-11e9-898a-21a9dca7aa58.png)

**Comment by thomashaenig** [comment]
it looks like you do not have the right to publish bookmarks. Can you check your security rules?
It is not possible to make a remote session for me, i am sorry
